backend:
  name: github
  repo: cellrin050-beep/CreateWebcellrin.github.io
  branch: main
  base_url: https://decap-cms-oauth.netlify.app

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}